### PR TITLE
OpenSSL v1.1 compatibility fix

### PR DESCRIPTION
**Pull request by hrobeers**
OpenSSL types cannot be stack allocated since v1.1
They are made opaque to the outside through forward declarations.

Fixes: https://github.com/matja/bitcoin-tool/issues/23

### CODE REVIEW

**Comment by matja** [comment]
Thanks for the fix! This brings compatibility with the latest versions of most Linux distributions.
An edge case I found is CentOS, latest version as of today is 7.4, which ships OpenSSL 1.0.2k-fips, an older branch will have to be used on that distro until I find a way to nicely support both API versions.
I've tested with OpenSSL 1.1.0f - all tests passed.

**Comment by hrobeers** [comment]
I believe this code should work with OpenSSL v1.0 too.
I did not test it though.

**Comment by hrobeers** [comment]
> BN_new(), BN_clear(), BN_free() and BN_clear_free() are available in all versions on SSLeay and OpenSSL. BN_init() was added in SSLeay 0.9.1b.

source: https://www.openssl.org/docs/man1.0.2/crypto/BN_new.html

**Comment by hrobeers** [comment]
@matja I just tested it against OpenSSL v1.0, all tests passed.

**Pull request merged**
